# Generated by Django 3.2.15 on 2025-08-28 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_occurrence', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_occurrence', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50)),
                ('total_predictions', models.IntegerField(default=0)),
                ('successful_predictions', models.IntegerField(default=0)),
                ('failed_predictions', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('low_confidence_count', models.IntegerField(default=0)),
                ('class_distribution', models.JSONField(default=dict)),
                ('avg_processing_time_ms', models.FloatField(blank=True, null=True)),
                ('max_processing_time_ms', models.FloatField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('avg_response_time_ms', models.FloatField()),
                ('min_response_time_ms', models.FloatField()),
                ('max_response_time_ms', models.FloatField()),
                ('p95_response_time_ms', models.FloatField()),
                ('p99_response_time_ms', models.FloatField()),
                ('request_count', models.IntegerField()),
                ('success_count', models.IntegerField()),
                ('error_count', models.IntegerField()),
                ('status_code_distribution', models.JSONField(default=dict)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_usage_percent', models.FloatField()),
                ('memory_usage_percent', models.FloatField()),
                ('disk_usage_percent', models.FloatField()),
                ('db_connections_active', models.IntegerField()),
                ('db_connections_max', models.IntegerField()),
                ('db_query_avg_time_ms', models.FloatField(blank=True, null=True)),
                ('cache_hit_rate', models.FloatField(blank=True, null=True)),
                ('cache_memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('celery_active_tasks', models.IntegerField(default=0)),
                ('celery_pending_tasks', models.IntegerField(default=0)),
                ('celery_failed_tasks', models.IntegerField(default=0)),
                ('api_avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('api_95th_percentile_ms', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create_patient', 'Crear paciente'), ('edit_patient', 'Editar paciente'), ('delete_patient', 'Eliminar paciente'), ('upload_image', 'Subir imagen'), ('process_image', 'Procesar imagen ML'), ('view_results', 'Ver resultados'), ('export_data', 'Exportar datos'), ('bulk_operation', 'Operación masiva')], max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='systemhealthmetrics',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_92bc13_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['endpoint', '-period_start'], name='monitoring__endpoin_7fdb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['-period_start'], name='monitoring__period__0d19bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('endpoint', 'method', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='mlmodelmetrics',
            index=models.Index(fields=['model_version', '-period_start'], name='monitoring__model_v_7540ca_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelmetrics',
            index=models.Index(fields=['-period_start'], name='monitoring__period__f7dba4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodelmetrics',
            unique_together={('model_version', 'period_start')},
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='monitoring__user_id_9d60aa_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action', '-timestamp'], name='monitoring__action_ed17c4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['ip_address', '-timestamp'], name='monitoring__ip_addr_eb0e26_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['success', '-timestamp'], name='monitoring__success_a557db_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['-last_occurrence'], name='monitoring__last_oc_ea6888_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_type', '-last_occurrence'], name='monitoring__error_t_492656_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['severity', '-last_occurrence'], name='monitoring__severit_03180a_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['resolved', '-last_occurrence'], name='monitoring__resolve_c8cdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['category', '-last_occurrence'], name='monitoring__categor_7a70e8_idx'),
        ),
    ]
