# Generated by Django 3.2.15 on 2025-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_clinica', models.CharField(max_length=100, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('tipo_diabetes', models.CharField(choices=[('tipo1', 'Tipo 1'), ('tipo2', 'Tipo 2'), ('desconocido', 'Se desconoce')], max_length=20)),
                ('estado_dilatacion', models.CharField(choices=[('dilatado', 'Dilatado'), ('no_dilatado', 'No dilatado')], max_length=20)),
                ('camara_retinal', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pacientes/')),
                ('resultado', models.IntegerField(blank=True, choices=[(0, 'Sin retinopatía'), (1, 'Leve'), (2, 'Moderada'), (3, 'Severa'), (4, 'Proliferativa')], null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
