# Generated by Django 3.2.15 on 2025-06-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='gradcam',
            field=models.ImageField(blank=True, null=True, upload_to='gradcams/'),
        ),
    ]
