# Generated by Django 3.2.15 on 2025-06-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_gradcam'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='confianza',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
