# Generated by Django 3.2.15 on 2025-06-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_confianza'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pacientes/')),
                ('gradcam', models.ImageField(blank=True, null=True, upload_to='gradcams/')),
                ('resultado', models.IntegerField(blank=True, choices=[(0, 'Sin retinopatía'), (1, 'Leve'), (2, 'Moderada'), (3, 'Severa'), (4, 'Proliferativa')], null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pacientes.paciente')),
            ],
        ),
    ]
