# Generated by Django 3.2.15 on 2025-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_imagenpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpaciente',
            name='gradcam_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
