# Generated by Django 3.2.15 on 2025-06-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_imagenpaciente_gradcam_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpaciente',
            name='imagen_procesada',
            field=models.ImageField(blank=True, null=True, upload_to='procesadas/'),
        ),
    ]
