# Generated by Django 3.2.15 on 2025-07-30 03:06

import apps.pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_imagenpaciente_imagen_procesada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenpaciente',
            options={'verbose_name': 'Imagen de Paciente', 'verbose_name_plural': 'Imágenes de Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='archivo_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='fecha_prediccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='imagen_preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='imagen_webp',
            field=models.ImageField(blank=True, null=True, upload_to='webp/'),
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='imagenpaciente',
            name='modelo_version',
            field=models.CharField(default='v2.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagenpaciente',
            name='imagen',
            field=models.ImageField(upload_to='pacientes/', validators=[apps.pacientes.validators.ImageValidator.validate_image_file]),
        ),
        migrations.AddIndex(
            model_name='imagenpaciente',
            index=models.Index(fields=['paciente', '-fecha_creacion'], name='pacientes_i_pacient_77b21d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenpaciente',
            index=models.Index(fields=['resultado'], name='pacientes_i_resulta_cb8409_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenpaciente',
            index=models.Index(fields=['fecha_prediccion'], name='pacientes_i_fecha_p_cd80e7_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenpaciente',
            index=models.Index(fields=['archivo_hash'], name='pacientes_i_archivo_d4586a_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['dni'], name='pacientes_p_dni_722873_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['historia_clinica'], name='pacientes_p_histori_791366_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nombres', 'apellidos'], name='pacientes_p_nombres_2b26b7_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['fecha_creacion'], name='pacientes_p_fecha_c_0aa913_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['resultado'], name='pacientes_p_resulta_e709c9_idx'),
        ),
    ]
