# Generated by Django 3.2.15 on 2025-09-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20250729_2206'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_p_dni_722873_idx',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='dni',
            new_name='ci',
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['ci'], name='pacientes_p_ci_64cadf_idx'),
        ),
    ]
