# Generated by Django 3.2.15 on 2025-07-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_useraccount_account'),
        ('api', '0002_update_roles'),
    ]

    operations = [
    ]
